setwd("/mnt/campus/math/research/kfouda/main/HEC/Melina/latest/cas_etude/")

library(Jmisc)
library(DiceEval)
library(parallel)
library(plotly)
library(mgcv)
library(Rcpp)
library(RColorBrewer)
library(ggpubr)
library(ZIprop)
library(corrplot)
library(tidyverse)
library(magrittr)

library(doParallel)
library(foreach)

sourceAll(path="../functions/")
source("./analyze_1_compute_p_values.R/")
source(".")